version: "3.9"
services:
  rabbitmq:
    container_name: vkrRabbitMqServer
    image: rabbitmq:3.11-management
    hostname: rabbitmq
    restart: always
        environment:
      - RABBITMQ_DEFAULT_USER=vkr
      - RABBITMQ_DEFAULT_PASS=vkr
    ports:
      - 15673:15672
      - 5673:5672